notifications:
  email: false

env:
  global:
    - TWINE_USERNAME=drbild
    # Note: TWINE_PASSWORD is set in Travis settings

matrix:
  include:
    - sudo: required
      services:
        - docker
      language: python
      install:
        - true
      script:
        - ./make/manylinux1/build_wheels.sh
        - |
          if [[ $TRAVIS_TAG ]]; then
            python -m pip install twine
            python -m twine upload dist/*.whl
          fi

    - os: osx
      osx_image: xcode9.3
      language: generic
      install:
        - ./make/osx/install_python.sh
      script:
        - ./make/osx/build_wheels.sh
        - |
          if [[ $TRAVIS_TAG ]]; then
            . ./venv_3.6/bin/activate
            python -m pip install twine
            python -m twine upload dist/*.whl
            deactive
          fi
